apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlbW86ZGVtb0Bwb3N0Z3Jlcy1jbHVzdGVyaXA6NTQzMi9kZW1v
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXBpLXAmJDN1cXJ0cHJfOGpvYiEqOTgkLV4hXnBeNGs9eHMqZjQjI2cwM2RjN29oaGpx
  DEBUG: VHJ1ZQ==
  ALLOWED_HOSTS: ZGVtby50ZXN0LDE5Mi4xNjguNTkuMTAzCg==
